class card():
    def __init__(self, title, condition):
        self.name = title
        self.cond = condition
        
def createCards(condition):
    cards = [
            # card("2023 Topps Chrome Anthony-Volpe Refractor PSA 10",condition["Graded"]),
            # card("2023 Topps Chrome Anthony-Volpe auto PSA 10", condition["Graded"]),
            # card("2020 Bowman Chrome Anthony-Volpe 1st auto PSA 10", condition["Graded"]),
            # card("2020 Bowman Chrome Anthony-Volpe 1st auto PSA 9", condition["Graded"]),
            # card("2023 Topps Chrome Adley-Rutschman Refractor PSA 10",condition["Graded"]),
            # card("2023 Topps Chrome Adley-Rutschman auto PSA 10",condition["Graded"]),
            # card("2019 Bowman Chrome Adley-Rutschman 1st auto PSA 10",condition["Graded"]),
            # card("2019 Bowman Chrome Adley-Rutschman 1st auto",condition["Ungraded"]),
            # card("2022 Topps Chrome Update Julio-Rodriguez USC150 PSA 10",condition["Graded"]),
            # card("2022 Topps Update Bobby-Witt-Jr USC35 PSA 10",condition["Graded"]),
            # card("2023 Bowman Draft Max-Clark 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Draft Max-Clark 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Draft Max-Clark BDC76 PSA 10",condition["Graded"]),
            # card("2020 Bowman Chrome 1st Luisangel-Acuna auto PSA 10",condition["Graded"]),
            # card("2020 Bowman Chrome 1st Luisangel-Acuna auto",condition["Ungraded"]),
            # card("2022 Bowman Draft Chase-DeLauter 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Draft Chase-DeLauter 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Chrome Jackson-Merrill 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Chrome Jackson-Merrill 1st auto",condition["Ungraded"]),
            # card("2021 Bowman Chrome Adael-Amador 1st auto PSA 10",condition["Graded"]),
            # card("2021 Bowman Chrome Adael-Amador 1st auto",condition["Ungraded"]),
            # card("2021 Bowman Draft Carson-Williams 1st auto PSA 10",condition["Graded"]),
            # card("2021 Bowman Draft Carson-Williams 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Draft Colt-Emerson 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Draft Colt-Emerson 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Chrome Colson-Montgomery 1st auto PSA 10",condition["Graded"]),
            card("2022 Bowman Chrome Colson-Montgomery 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Chrome Curtis-Mead 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Chrome Curtis-Mead 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Draft Jett-Williams 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Draft Jett-Williams 1st auto",condition["Ungraded"]),
            # card("2021 Bowman Draft Jordan-Lawlar 1st auto PSA 10",condition["Graded"]),
            # card("2021 Bowman Draft Jordan-Lawlar 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Chrome James-Wood 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Chrome James-Wood 1st auto",condition["Ungraded"]),
            # card("2020 Bowman Chrome Jasson-Dominguez 1st auto PSA 10",condition["Graded"]),
            # card("2020 Bowman Chrome Jasson-Dominguez 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Draft Matt-Shaw 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Draft Matt-Shaw 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Chrome Roman-Anthony 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Chrome Roman-Anthony 1st auto",condition["Ungraded"]),
            # card("2021 Bowman Chrome Coby-Mayo 1st auto PSA 10",condition["Graded"]),
            # card("2021 Bowman Chrome Coby-Mayo 1st auto",condition["Ungraded"]),
            # card("2020 Bowman Draft Colt-Keith 1st auto PSA 10",condition["Graded"]),
            # card("2020 Bowman Draft Colt-Keith 1st auto",condition["Ungraded"]),
            # card("2019 Bowman Chrome Noelvi-Marte 1st auto PSA 10",condition["Graded"]),
            # card("2019 Bowman Chrome Noelvi-Marte 1st auto",condition["Ungraded"]),
            # card("2020 Bowman Draft Pete-Crow-Armstrong 1st auto PSA 10",condition["Graded"]), 
            # card("2020 Bowman Draft Pete-Crow-Armstrong 1st auto",condition["Ungraded"]), 
            # card("2023 Bowman Chrome Samuel-Basallo 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Chrome Samuel-Basallo 1st auto",condition["Ungraded"]),
            # card("2020 Bowman Draft Evan-Carter 1st auto PSA 10",condition["Graded"]),
            # card("2020 Bowman Draft Evan-Carter 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Chrome Ethan-Salas 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Chrome Ethan-Salas 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Chrome Junior-Caminero 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Chrome Junior-Caminero 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Draft Wyatt-Langford 1st auto PSA 10",condition["Graded"]),
            # card("2023 Bowman Draft Wyatt-Langford 1st auto",condition["Ungraded"]),
            # card("2023 Bowman Draft Wyatt-Langford Chrome 1st PSA 10",condition["Graded"]),
            # card("2022 Bowman Chrome Jackson-Chourio 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Chrome Jackson-Chourio 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Chrome Jackson-Chourio 1st PSA 10",condition["Graded"]),
            # card("2022 Bowman Draft Jackson-Holiday 1st auto PSA 10",condition["Graded"]),
            # card("2022 Bowman Draft Jackson-Holiday 1st auto",condition["Ungraded"]),
            # card("2022 Bowman Draft Jackson-Holiday 1st PSA 10",condition["Graded"])
            ]
    return cards